-- Deploy the PlayNova policy console as Streamlit-in-Snowflake.
CREATE STAGE IF NOT EXISTS PLAYNOVA_RECS_DEMO.APP.STREAMLIT_STAGE DIRECTORY=(ENABLE=TRUE);
PUT file://streamlit/policy_console.py @PLAYNOVA_RECS_DEMO.APP.STREAMLIT_STAGE/policy_console OVERWRITE=TRUE AUTO_COMPRESS=FALSE;
CREATE OR REPLACE STREAMLIT PLAYNOVA_RECS_DEMO.APP.POLICY_CONSOLE
  ROOT_LOCATION = '@PLAYNOVA_RECS_DEMO.APP.STREAMLIT_STAGE/policy_console'
  MAIN_FILE = 'policy_console.py'
  QUERY_WAREHOUSE = COMPUTE_WH
  COMMENT = 'PlayNova policy console';
