-- ============================================================================
-- PlayNova Demo - Feature Store RBAC + online-service prerequisites
-- Creates producer/consumer roles with the privileges required by the Feature
-- Store and the Online Feature Store (Postgres) preview. Run as ACCOUNTADMIN.
-- Ref: docs feature-store/rbac + create-and-serve-online-features.
-- ============================================================================
SET FS_ROLE_PRODUCER = 'PLAYNOVA_FS_PRODUCER';
SET FS_ROLE_CONSUMER = 'PLAYNOVA_FS_CONSUMER';
SET FS_DATABASE = 'PLAYNOVA_RECS_DEMO';
SET FS_SCHEMA   = 'FEATURES';
SET FS_WAREHOUSE = 'COMPUTE_WH';
SET SCHEMA_FQN = CONCAT($FS_DATABASE, '.', $FS_SCHEMA);
SET CORE_FQN   = CONCAT($FS_DATABASE, '.CORE');
SET CURRENT_USER_NAME = CURRENT_USER();

CREATE ROLE IF NOT EXISTS IDENTIFIER($FS_ROLE_PRODUCER);
CREATE ROLE IF NOT EXISTS IDENTIFIER($FS_ROLE_CONSUMER);

-- Role hierarchy: consumer -> producer -> SYSADMIN; expose to ACCOUNTADMIN + me.
GRANT ROLE IDENTIFIER($FS_ROLE_CONSUMER) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
GRANT ROLE IDENTIFIER($FS_ROLE_PRODUCER) TO ROLE SYSADMIN;
GRANT ROLE IDENTIFIER($FS_ROLE_PRODUCER) TO ROLE ACCOUNTADMIN;
GRANT ROLE IDENTIFIER($FS_ROLE_PRODUCER) TO USER IDENTIFIER($CURRENT_USER_NAME);

-- Producer privileges on the feature-store schema.
GRANT CREATE DYNAMIC TABLE ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
GRANT CREATE VIEW          ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
GRANT CREATE TAG           ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
GRANT CREATE DATASET       ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
GRANT CREATE TABLE         ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);
-- Online Feature Store (Postgres) preview: online feature tables.
GRANT CREATE ONLINE FEATURE TABLE ON SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);

-- Consumer privileges (producer inherits these).
GRANT USAGE ON DATABASE IDENTIFIER($FS_DATABASE) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON SCHEMA   IDENTIFIER($SCHEMA_FQN)  TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, MONITOR ON ALL    DYNAMIC TABLES IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, REFERENCES ON ALL    VIEWS IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON FUTURE DATASETS IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON ALL    DATASETS IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, MONITOR ON FUTURE ONLINE FEATURE TABLES IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT, MONITOR ON ALL    ONLINE FEATURE TABLES IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($FS_WAREHOUSE) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($FS_WAREHOUSE) TO ROLE IDENTIFIER($FS_ROLE_PRODUCER);

-- Allow feature-view backfill to read CORE source tables.
GRANT USAGE ON SCHEMA IDENTIFIER($CORE_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($CORE_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT SELECT ON ALL    TABLES IN SCHEMA IDENTIFIER($CORE_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);

-- Change tracking on stream backfill source (needed for incremental refresh).
ALTER TABLE PLAYNOVA_RECS_DEMO.CORE.GAME_ROUND_FACT SET CHANGE_TRACKING = TRUE;
ALTER TABLE PLAYNOVA_RECS_DEMO.RAW.GAMEPLAY_EVENTS  SET CHANGE_TRACKING = TRUE;
